# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Run the welcome/run job in its own container
orbs:
  ruby: circleci/ruby@0.1.2 
jobs:
  build:
     docker:
       - image: circleci/ruby:2.4.1-node-browsers
     steps:
       - checkout
       - run:
          name: Which bundler?
          command: bundle -v
       - ruby/bundle-install
       - run:
          name: build dependencies
          command: bundle install
       - run:
           name: Greeting
           command: echo Hello, world.
       - run: 
           name: Print the Current Time
           command: date
       - run:
           name: build the jekyll site
           command: bundle exec jekyll build
